### ISSUE TITLE
Migrate from ImageField to ThumbnailerImageField...

### ISSUE THREAD

**Issue by milonline-eu** [modbender/easy-thumbnails-rest#9]
https://github.com/modbender/easy-thumbnails-rest/pull/3/commits/c34d0ed34d7af604d8c5c884f0154d5278724ea4

...concerning the 'bool(instance)' you took out. When migrating from Django's ImageField to ThumbnailerImageField I'm getting error:
```
Traceback (most recent call last):
  File "/srv/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/srv/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/srv/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/lesycr-knl-be/releases/20210523141549/django/news/views.py", line 47, in list
    return Response(newsSerializer.data)
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 1870, in to_representation
    return method(value)
  File "/srv/lesycr-knl-be/releases/20210523141549/django/news/serializers.py", line 52, in get_gallery
    return FileSerializer(fileList, many=True, context={'request': self.context.get('request')}).data
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/srv/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/srv/venv/lib/python3.8/site-packages/easy_thumbnails_rest/serializers.py", line 60, in to_representation
    return list(image_sizes(self.context['request'], instance, self.alias_obj, self.alias).values())
  File "/srv/venv/lib/python3.8/site-packages/easy_thumbnails_rest/serializers.py", line 26, in image_sizes
    'original': get_url(request, instance),
  File "/srv/venv/lib/python3.8/site-packages/easy_thumbnails_rest/serializers.py", line 17, in get_url
    return request.build_absolute_uri(instance.url)
  File "/srv/venv/lib/python3.8/site-packages/django/db/models/fields/files.py", line 61, in url
    self._require_file()
  File "/srv/venv/lib/python3.8/site-packages/django/db/models/fields/files.py", line 38, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'imageUri' attribute has no file associated with it.
```

With bool, all is fine.
Then when reverting back to non bool version it's working fine too.

I guess it's something with thumbnails generation...

**Comment by modbender** [comment]
Alright I'll check it out.

**Comment by modbender** [comment]
@milonline-eu Sorry for the late, covid has really messed up a lot of things, either way I have released a new version just now. If you are still in wait or having free time you could check it out.

**Comment by modbender** [comment]
I have checked and verified many times and this issue has been patched, so I'm closing it.
